alter table HELTHDIARY_PATIENT add constraint FK_HELTHDIARY_PATIENT_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_HELTHDIARY_PATIENT_ON_USER on HELTHDIARY_PATIENT (USER_ID);
