alter table HELTHDIARY_TEMPERATURE add constraint FK_HELTHDIARY_TEMPERATURE_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_HELTHDIARY_TEMPERATURE_ON_USER on HELTHDIARY_TEMPERATURE (USER_ID);
