-- begin HELTHDIARY_PATIENT
alter table HELTHDIARY_PATIENT add constraint FK_HELTHDIARY_PATIENT_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_HELTHDIARY_PATIENT_UK_USER_ID on HELTHDIARY_PATIENT (USER_ID) where DELETE_TS is null ^
create index IDX_HELTHDIARY_PATIENT_ON_USER on HELTHDIARY_PATIENT (USER_ID)^
-- end HELTHDIARY_PATIENT
-- begin HELTHDIARY_PRESSURE
alter table HELTHDIARY_PRESSURE add constraint FK_HELTHDIARY_PRESSURE_ON_PATIENT foreign key (PATIENT_ID) references HELTHDIARY_PATIENT(ID)^
create index IDX_HELTHDIARY_PRESSURE_ON_PATIENT on HELTHDIARY_PRESSURE (PATIENT_ID)^
-- end HELTHDIARY_PRESSURE
-- begin HELTHDIARY_PULSE
alter table HELTHDIARY_PULSE add constraint FK_HELTHDIARY_PULSE_ON_PATIENT foreign key (PATIENT_ID) references HELTHDIARY_PATIENT(ID)^
create index IDX_HELTHDIARY_PULSE_ON_PATIENT on HELTHDIARY_PULSE (PATIENT_ID)^
-- end HELTHDIARY_PULSE
-- begin HELTHDIARY_TEMPERATURE
alter table HELTHDIARY_TEMPERATURE add constraint FK_HELTHDIARY_TEMPERATURE_ON_PATIENT foreign key (PATIENT_ID) references HELTHDIARY_PATIENT(ID)^
create index IDX_HELTHDIARY_TEMPERATURE_ON_PATIENT on HELTHDIARY_TEMPERATURE (PATIENT_ID)^
-- end HELTHDIARY_TEMPERATURE
-- begin HELTHDIARY_DOCTOR
alter table HELTHDIARY_DOCTOR add constraint FK_HELTHDIARY_DOCTOR_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_HELTHDIARY_DOCTOR_ON_USER on HELTHDIARY_DOCTOR (USER_ID)^
-- end HELTHDIARY_DOCTOR
-- begin HELTHDIARY_GLUCOSE
alter table HELTHDIARY_GLUCOSE add constraint FK_HELTHDIARY_GLUCOSE_ON_PATIENT foreign key (PATIENT_ID) references HELTHDIARY_PATIENT(ID)^
create index IDX_HELTHDIARY_GLUCOSE_ON_PATIENT on HELTHDIARY_GLUCOSE (PATIENT_ID)^
-- end HELTHDIARY_GLUCOSE
-- begin HELTHDIARY_VISIT
alter table HELTHDIARY_VISIT add constraint FK_HELTHDIARY_VISIT_ON_PATIENT foreign key (PATIENT_ID) references HELTHDIARY_PATIENT(ID)^
alter table HELTHDIARY_VISIT add constraint FK_HELTHDIARY_VISIT_ON_DOCTOR foreign key (DOCTOR_ID) references HELTHDIARY_DOCTOR(ID)^
create index IDX_HELTHDIARY_VISIT_ON_PATIENT on HELTHDIARY_VISIT (PATIENT_ID)^
create index IDX_HELTHDIARY_VISIT_ON_DOCTOR on HELTHDIARY_VISIT (DOCTOR_ID)^
-- end HELTHDIARY_VISIT
