-- begin HELTHDIARY_PRESSURE
alter table HELTHDIARY_PRESSURE add constraint FK_HELTHDIARY_PRESSURE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_HELTHDIARY_PRESSURE_ON_USER on HELTHDIARY_PRESSURE (USER_ID)^
-- end HELTHDIARY_PRESSURE
-- begin HELTHDIARY_PULSE
alter table HELTHDIARY_PULSE add constraint FK_HELTHDIARY_PULSE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_HELTHDIARY_PULSE_ON_USER on HELTHDIARY_PULSE (USER_ID)^
-- end HELTHDIARY_PULSE
-- begin HELTHDIARY_GLUCOSE
alter table HELTHDIARY_GLUCOSE add constraint FK_HELTHDIARY_GLUCOSE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_HELTHDIARY_GLUCOSE_ON_USER on HELTHDIARY_GLUCOSE (USER_ID)^
-- end HELTHDIARY_GLUCOSE
-- begin HELTHDIARY_SLEEP
alter table HELTHDIARY_SLEEP add constraint FK_HELTHDIARY_SLEEP_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_HELTHDIARY_SLEEP_ON_USER on HELTHDIARY_SLEEP (USER_ID)^
-- end HELTHDIARY_SLEEP
